"""Noms d'événements centralisés — convention module.entity.action.vN."""

from __future__ import annotations


class EventNames:
    """Constantes stables pour le bus (pas de chaînes dispersées)."""

    VAULT_DOCUMENT_ARCHIVED = "vault.document.archived.v1"
    VAULT_DOCUMENT_REUSED = "vault.document.reused.v1"

    DELIVERY_EMAIL_STARTED = "delivery.email.started.v1"
    DELIVERY_EMAIL_SENT = "delivery.email.sent.v1"
    DELIVERY_EMAIL_FAILED = "delivery.email.failed.v1"

    # Facturation commerciale (devis/factures clients)
    BILLING_INVOICE_CREATED = "billing.invoice.created.v1"
    BILLING_INVOICE_SENT = "billing.invoice.sent.v1"
    BILLING_QUOTE_SENT = "billing.quote.sent.v1"
    BILLING_CREDIT_NOTE_SENT = "billing.credit_note.sent.v1"

    # Abonnements / entitlements / quotas (SaaS)
    BILLING_SUBSCRIPTION_CREATED = "billing.subscription.created.v1"
    BILLING_SUBSCRIPTION_TRIAL_STARTED = "billing.subscription.trial_started.v1"
    BILLING_SUBSCRIPTION_TRIAL_ENDING = "billing.subscription.trial_ending.v1"
    BILLING_SUBSCRIPTION_ACTIVATED = "billing.subscription.activated.v1"
    BILLING_SUBSCRIPTION_UPDATED = "billing.subscription.updated.v1"
    BILLING_SUBSCRIPTION_PAST_DUE = "billing.subscription.past_due.v1"
    BILLING_SUBSCRIPTION_PAYMENT_FAILED = "billing.subscription.payment_failed.v1"
    BILLING_SUBSCRIPTION_PAYMENT_SUCCEEDED = "billing.subscription.payment_succeeded.v1"
    BILLING_SUBSCRIPTION_CANCEL_SCHEDULED = "billing.subscription.cancel_scheduled.v1"
    BILLING_SUBSCRIPTION_CANCELLED = "billing.subscription.cancelled.v1"
    BILLING_SUBSCRIPTION_EXPIRED = "billing.subscription.expired.v1"
    BILLING_SUBSCRIPTION_SUSPENDED = "billing.subscription.suspended.v1"
    BILLING_SUBSCRIPTION_REACTIVATED = "billing.subscription.reactivated.v1"
    BILLING_ENTITLEMENTS_UPDATED = "billing.entitlements.updated.v1"
    BILLING_QUOTA_WARNING = "billing.quota.warning.v1"
    BILLING_QUOTA_EXCEEDED = "billing.quota.exceeded.v1"
    BILLING_USAGE_RECORDED = "billing.usage.recorded.v1"

    NOTIFICATION_CREATED = "notification.created.v1"
    NOTIFICATION_EMAIL_REQUESTED = "notification.email.requested.v1"
    NOTIFICATION_EMAIL_SENT = "notification.email.sent.v1"
    NOTIFICATION_EMAIL_FAILED = "notification.email.failed.v1"
    NOTIFICATION_READ = "notification.read.v1"

    JOB_CREATED = "job.created.v1"
    JOB_STARTED = "job.started.v1"
    JOB_PROGRESS = "job.progress.v1"
    JOB_COMPLETED = "job.completed.v1"
    JOB_RETRY_SCHEDULED = "job.retry_scheduled.v1"
    JOB_FAILED = "job.failed.v1"
    JOB_DEAD_LETTERED = "job.dead_lettered.v1"
    JOB_CANCELLED = "job.cancelled.v1"
    JOB_TIMED_OUT = "job.timed_out.v1"
    JOB_RETRIED = "job.retried.v1"

    AI_EXECUTION_CREATED = "ai.execution.created.v1"
    AI_EXECUTION_STARTED = "ai.execution.started.v1"
    AI_EXECUTION_COMPLETED = "ai.execution.completed.v1"
    AI_EXECUTION_FAILED = "ai.execution.failed.v1"
    AI_EXECUTION_REQUIRES_REVIEW = "ai.execution.requires_review.v1"
    AI_USAGE_RECORDED = "ai.usage.recorded.v1"
    DOCUMENT_ANALYSIS_COMPLETED = "document.analysis.completed.v1"

    DOCUMENT_EXTRACTION_CREATED = "document.extraction.created.v1"
    DOCUMENT_EXTRACTION_STARTED = "document.extraction.started.v1"
    DOCUMENT_EXTRACTION_COMPLETED = "document.extraction.completed.v1"
    DOCUMENT_EXTRACTION_REQUIRES_OCR = "document.extraction.requires_ocr.v1"
    DOCUMENT_EXTRACTION_FAILED = "document.extraction.failed.v1"
    DOCUMENT_EXTRACTION_REQUIRES_REVIEW = "document.extraction.requires_review.v1"

    ACCOUNTING_PROPOSAL_CREATED = "accounting.proposal.created.v1"
    ACCOUNTING_PROPOSAL_PROCESSING = "accounting.proposal.processing.v1"
    ACCOUNTING_PROPOSAL_READY = "accounting.proposal.ready.v1"
    ACCOUNTING_PROPOSAL_REQUIRES_REVIEW = "accounting.proposal.requires_review.v1"
    ACCOUNTING_PROPOSAL_VALIDATION_FAILED = "accounting.proposal.validation_failed.v1"
    ACCOUNTING_PROPOSAL_UNBALANCED = "accounting.proposal.unbalanced.v1"
    ACCOUNTING_PROPOSAL_UPDATED = "accounting.proposal.updated.v1"
    ACCOUNTING_PROPOSAL_VALIDATED = "accounting.proposal.validated.v1"
    ACCOUNTING_PROPOSAL_REJECTED = "accounting.proposal.rejected.v1"
    ACCOUNTING_PROPOSAL_REOPENED = "accounting.proposal.reopened.v1"

    # Accounting Engine V2
    ACCOUNTING_ENGINE_PROPOSAL_GENERATED = "accounting_engine.proposal.generated.v1"
    ACCOUNTING_ENGINE_PROPOSAL_REGENERATED = "accounting_engine.proposal.regenerated.v1"
    ACCOUNTING_ENGINE_PROPOSAL_REQUIRES_REVIEW = "accounting_engine.proposal.requires_review.v1"

    # Accounting Intelligence V2
    ACCOUNTING_INTELLIGENCE_LEARNING_CREATED = "learning.created.v1"
    ACCOUNTING_INTELLIGENCE_FEEDBACK_RECEIVED = "feedback.received.v1"
    ACCOUNTING_INTELLIGENCE_RECOMMENDATION_GENERATED = "recommendation.generated.v1"
    ACCOUNTING_INTELLIGENCE_RECOMMENDATION_ACCEPTED = "recommendation.accepted.v1"
    ACCOUNTING_INTELLIGENCE_RECOMMENDATION_MODIFIED = "recommendation.modified.v1"
    ACCOUNTING_INTELLIGENCE_RECOMMENDATION_REJECTED = "recommendation.rejected.v1"

    SEARCH_INDEX_REQUESTED = "search.index.requested.v1"
    SEARCH_DOCUMENT_INDEXED = "search.document.indexed.v1"
    SEARCH_DOCUMENT_UPDATED = "search.document.updated.v1"
    SEARCH_DOCUMENT_REMOVED = "search.document.removed.v1"
    SEARCH_INDEX_FAILED = "search.index.failed.v1"
    SEARCH_ORGANIZATION_REINDEX_STARTED = "search.organization.reindex.started.v1"
    SEARCH_ORGANIZATION_REINDEX_COMPLETED = "search.organization.reindex.completed.v1"

    PLATFORM_ORGANIZATION_SUSPENDED = "platform.organization.suspended.v1"
    PLATFORM_ORGANIZATION_RESTORED = "platform.organization.restored.v1"

    WORKSPACE_PROVISION_STARTED = "workspace.provision.started.v1"
    WORKSPACE_PROVISION_COMPANY_PROFILE_SAVED = "workspace.provision.company_profile_saved.v1"
    WORKSPACE_PROVISION_SETTINGS_CONFIGURED = "workspace.provision.settings_configured.v1"
    WORKSPACE_PROVISION_COMPLETED = "workspace.provision.completed.v1"
    WORKSPACE_PROVISION_FAILED = "workspace.provision.failed.v1"
    PLATFORM_USER_DISABLED = "platform.user.disabled.v1"
    PLATFORM_USER_ENABLED = "platform.user.enabled.v1"
    PLATFORM_JOB_MANUAL_RETRY = "platform.job.manual_retry.v1"
    PLATFORM_EVENT_MANUAL_RETRY = "platform.event.manual_retry.v1"
    PLATFORM_INCIDENT_ACKNOWLEDGED = "platform.incident.acknowledged.v1"
    PLATFORM_INCIDENT_RESOLVED = "platform.incident.resolved.v1"
    PLATFORM_ENTITLEMENT_OVERRIDDEN = "platform.entitlement.overridden.v1"
    PLATFORM_QUOTA_OVERRIDDEN = "platform.quota.overridden.v1"

    SECURITY_AUTHENTICATION_FAILED = "security.authentication.failed.v1"
    SECURITY_PERMISSION_DENIED = "security.permission.denied.v1"
    SECURITY_RATE_LIMIT_EXCEEDED = "security.rate_limit.exceeded.v1"
    SECURITY_WEBHOOK_INVALID_SIGNATURE = "security.webhook.invalid_signature.v1"
    SECURITY_PAYLOAD_REJECTED = "security.payload.rejected.v1"
    SECURITY_CROSS_TENANT_ATTEMPT = "security.cross_tenant.attempt.v1"
    RELIABILITY_STALE_JOB_DETECTED = "reliability.stale_job.detected.v1"
    RELIABILITY_STALE_EVENT_DETECTED = "reliability.stale_event.detected.v1"
    RELIABILITY_CLEANUP_COMPLETED = "reliability.cleanup.completed.v1"
    RELIABILITY_HEALTH_DEGRADED = "reliability.health.degraded.v1"
    RELIABILITY_HEALTH_RESTORED = "reliability.health.restored.v1"

    # Assistant de Migration
    MIGRATION_SESSION_CREATED = "migration.session.created.v1"
    MIGRATION_PROFILE_UPDATED = "migration.profile.updated.v1"
    MIGRATION_SOURCES_UPDATED = "migration.sources.updated.v1"
    MIGRATION_STEP_STARTED = "migration.step.started.v1"
    MIGRATION_STEP_COMPLETED = "migration.step.completed.v1"
    MIGRATION_SESSION_RESUMED = "migration.session.resumed.v1"
    MIGRATION_SESSION_CANCELLED = "migration.session.cancelled.v1"
    MIGRATION_PROGRESS_UPDATED = "migration.progress.updated.v1"
    MIGRATION_ACTIVITY_RECORDED = "migration.activity.recorded.v1"

    # Document Intake Engine
    DOCUMENT_UPLOADED = "document.uploaded.v1"
    DOCUMENT_VALIDATED = "document.validated.v1"
    DOCUMENT_REJECTED = "document.rejected.v1"
    DOCUMENT_DUPLICATE_DETECTED = "document.duplicate_detected.v1"
    DOCUMENT_READY_FOR_ANALYSIS = "document.ready_for_analysis.v1"
    DOCUMENT_LIFECYCLE_CHANGED = "document.lifecycle.changed.v1"
    DOCUMENT_UPLOAD_SESSION_CREATED = "document.upload_session.created.v1"
    DOCUMENT_UPLOAD_SESSION_STARTED = "document.upload_session.started.v1"
    DOCUMENT_UPLOAD_SESSION_PAUSED = "document.upload_session.paused.v1"
    DOCUMENT_UPLOAD_SESSION_RESUMED = "document.upload_session.resumed.v1"
    DOCUMENT_UPLOAD_SESSION_COMPLETED = "document.upload_session.completed.v1"
    DOCUMENT_UPLOAD_SESSION_CANCELLED = "document.upload_session.cancelled.v1"
    DOCUMENT_UPLOAD_ANALYTICS_UPDATED = "document.upload.analytics.updated.v1"
    DOCUMENT_FINGERPRINT_CREATED = "document.fingerprint.created.v1"
    DOCUMENT_ANALYSIS_STARTED = "document.analysis.started.v1"
    DOCUMENT_ANALYSIS_COMPLETED = "document.analysis.completed.v1"
    DOCUMENT_ANALYSIS_FAILED = "document.analysis.failed.v1"
    DOCUMENT_ANALYSIS_READY_FOR_AI = "document.analysis.ready_for_ai.v1"
    DOCUMENT_EXTRACTION_REQUESTED = "document.extraction.requested.v1"
    DOCUMENT_EXTRACTION_QUEUED = "document.extraction.queued.v1"
    DOCUMENT_EXTRACTION_STARTED = "document.extraction.started.v1"
    DOCUMENT_EXTRACTION_PROGRESSED = "document.extraction.progressed.v1"
    DOCUMENT_EXTRACTION_COMPLETED = "document.extraction.completed.v1"
    DOCUMENT_EXTRACTION_COMPLETED_WITH_WARNINGS = "document.extraction.completed_with_warnings.v1"
    DOCUMENT_EXTRACTION_FAILED = "document.extraction.failed.v1"
    DOCUMENT_EXTRACTION_CANCELLED = "document.extraction.cancelled.v1"
    DOCUMENT_EXTRACTION_AWAITING_VALIDATION = "document.extraction.awaiting_validation.v1"
    DOCUMENT_EXTRACTION_QUOTA_EXCEEDED = "document.extraction.quota_exceeded.v1"

    VALIDATION_STARTED = "validation.started.v1"
    VALIDATION_FIELD_EDITED = "field.edited.v1"
    VALIDATION_FIELD_ACCEPTED = "field.accepted.v1"
    VALIDATION_DOCUMENT_VALIDATED = "document.validated.v1"
    VALIDATION_DOCUMENT_REJECTED = "document.rejected.v1"
    VALIDATION_DUPLICATE_DETECTED = "duplicate.detected.v1"
    VALIDATION_MATCHING_COMPLETED = "matching.completed.v1"
    VALIDATION_READY_FOR_IMPORT = "ready_for_import.v1"

    # Import Engine (Sprint 6)
    IMPORT_STARTED = "import.started.v1"
    IMPORT_MAPPING_COMPLETED = "import.mapping.completed.v1"
    IMPORT_TRANSACTION_STARTED = "import.transaction.started.v1"
    IMPORT_TRANSACTION_COMMITTED = "import.transaction.committed.v1"
    IMPORT_COMPLETED = "import.completed.v1"
    IMPORT_FAILED = "import.failed.v1"
    IMPORT_ROLLBACK_STARTED = "rollback.started.v1"
    IMPORT_ROLLBACK_COMPLETED = "rollback.completed.v1"

    # Banking Platform V1
    BANKING_CONNECTION_CONNECTED = "banking.connection.connected.v1"
    BANKING_CONNECTION_DISCONNECTED = "banking.connection.disconnected.v1"
    BANKING_TRANSACTION_CREATED = "banking.transaction.created.v1"
    BANKING_TRANSACTION_UPDATED = "banking.transaction.updated.v1"
    BANKING_SYNC_COMPLETED = "banking.sync.completed.v1"
    BANKING_SYNC_FAILED = "banking.sync.failed.v1"
    BANKING_CONSENT_EXPIRING = "banking.consent.expiring.v1"
    BANKING_REAUTHENTICATION_REQUIRED = "banking.reauthentication.required.v1"
    BANKING_CONNECTION_REAUTHENTICATED = "banking.connection.reauthenticated.v1"
    BANKING_CONNECTION_REVOKED = "banking.connection.revoked.v1"

    # Financial Dashboard V1
    FINANCIAL_HEALTH_UPDATED = "financial.health.updated.v1"
    FINANCIAL_ALERT_CREATED = "financial.alert.created.v1"
    FINANCIAL_KPI_UPDATED = "financial.kpi.updated.v1"

    # AI Financial Assistant V1
    AI_ASSISTANT_CHAT_COMPLETED = "ai.assistant.chat.completed.v1"
    AI_ASSISTANT_FEEDBACK_RECORDED = "ai.assistant.feedback.recorded.v1"

    # Decision Center V1
    DECISION_CREATED = "decision.created.v1"
    DECISION_UPDATED = "decision.updated.v1"
    DECISION_RESOLVED = "decision.resolved.v1"
    DECISION_DISMISSED = "decision.dismissed.v1"
    DECISION_EXECUTION_STARTED = "decision.execution.started.v1"
    DECISION_EXECUTION_SUCCEEDED = "decision.execution.succeeded.v1"
    DECISION_EXECUTION_FAILED = "decision.execution.failed.v1"
    DECISION_STARTED = "decision.started.v1"
    DECISION_REOPENED = "decision.reopened.v1"

    # Smart Migration (Sprint 7)
    SMART_MIGRATION_STARTED = "migration.started.v1"
    SMART_MIGRATION_PROGRESS = "migration.progress.v1"
    SMART_MIGRATION_COMPLETED = "migration.completed.v1"
    SMART_MIGRATION_FAILED = "migration.failed.v1"
    SMART_MIGRATION_CANCELLED = "migration.cancelled.v1"
    SMART_MIGRATION_RESUMED = "migration.resumed.v1"
    SMART_MIGRATION_REPORT_READY = "migration.report.ready.v1"

    # SalesPilot CRM Foundation V1
    SALES_LEAD_CREATED = "sales.lead.created.v1"
    SALES_COMPANY_CREATED = "sales.company.created.v1"
    SALES_PERSON_CREATED = "sales.person.created.v1"
    SALES_OPPORTUNITY_CREATED = "sales.opportunity.created.v1"
    SALES_OPPORTUNITY_UPDATED = "sales.opportunity.updated.v1"
    SALES_OPPORTUNITY_STAGE_CHANGED = "sales.opportunity.stage_changed.v1"
    SALES_TASK_CREATED = "sales.task.created.v1"
    SALES_TASK_COMPLETED = "sales.task.completed.v1"
    SALES_ACTIVITY_CREATED = "sales.activity.created.v1"
    # Aliases documentés S1.3 (mêmes événements)
    SALES_ACTIVITY_ADDED = SALES_ACTIVITY_CREATED
    SALES_TASK_ADDED = SALES_TASK_CREATED

    # Relationship Workspace S1.4
    SALES_WORKSPACE_OPENED = "sales.workspace.opened.v1"
    SALES_RELATIONSHIP_UPDATED = "sales.relationship.updated.v1"
    SALES_TIMELINE_UPDATED = "sales.timeline.updated.v1"

    # Deal Workspace S1.5
    SALES_DEAL_OPENED = "sales.deal.opened.v1"
    SALES_FORECAST_UPDATED = "sales.forecast.updated.v1"
    SALES_PRODUCT_ADDED = "sales.product.added.v1"
    SALES_PRODUCT_REMOVED = "sales.product.removed.v1"

    # Commercial Proposal Engine S1.6
    SALES_PROPOSAL_CREATED = "sales.proposal.created.v1"
    SALES_PROPOSAL_VERSION_CREATED = "sales.proposal.version.created.v1"
    SALES_PROPOSAL_VERSION_LOCKED = "sales.proposal.version.locked.v1"
    SALES_PROPOSAL_PDF_GENERATED = "sales.proposal.pdf.generated.v1"
    SALES_PROPOSAL_REVIEW_REQUESTED = "sales.proposal.review.requested.v1"
    SALES_PROPOSAL_APPROVED = "sales.proposal.approved.v1"
    SALES_PROPOSAL_SENT = "sales.proposal.sent.v1"
    SALES_PROPOSAL_VIEWED = "sales.proposal.viewed.v1"
    SALES_PROPOSAL_NEGOTIATION_STARTED = "sales.proposal.negotiation.started.v1"
    SALES_PROPOSAL_ACCEPTED = "sales.proposal.accepted.v1"
    SALES_PROPOSAL_REJECTED = "sales.proposal.rejected.v1"
    SALES_PROPOSAL_EXPIRED = "sales.proposal.expired.v1"
    SALES_PROPOSAL_CONVERSION_PREPARED = "sales.proposal.conversion.prepared.v1"
    SALES_PROPOSAL_CUSTOMER_LINKED = "sales.proposal.customer.linked.v1"
    SALES_PROPOSAL_CUSTOMER_CREATED = "sales.proposal.customer.created.v1"
    SALES_PROPOSAL_CONVERSION_STARTED = "sales.proposal.conversion.started.v1"
    SALES_PROPOSAL_CONVERTED = "sales.proposal.converted.v1"
    SALES_PROPOSAL_CONVERSION_FAILED = "sales.proposal.conversion.failed.v1"
    BILLING_INVOICE_CREATED_FROM_PROPOSAL = "billing.invoice.created_from_proposal.v1"
    SALES_INSIGHT_CREATED = "sales.insight.created.v1"
    SALES_INSIGHT_UPDATED = "sales.insight.updated.v1"
    SALES_INSIGHT_RESOLVED = "sales.insight.resolved.v1"
    SALES_INSIGHT_ACKNOWLEDGED = "sales.insight.acknowledged.v1"
    SALES_INSIGHT_DISMISSED = "sales.insight.dismissed.v1"
    SALES_FOCUS_CHANGED = "sales.focus.changed.v1"
    SALES_DUPLICATE_IGNORED = "sales.duplicate.ignored.v1"
    SALES_BULK_ACTION_APPLIED = "sales.bulk.action.applied.v1"
    SALES_IMPORT_COMPLETED = "sales.import.completed.v1"

    # Sales Collaboration S1.9
    SALES_TEAM_CREATED = "sales.team.created.v1"
    SALES_TEAM_UPDATED = "sales.team.updated.v1"
    SALES_TEAM_MEMBER_ADDED = "sales.team.member_added.v1"
    SALES_COMMENT_CREATED = "sales.comment.created.v1"
    SALES_COMMENT_UPDATED = "sales.comment.updated.v1"
    SALES_COMMENT_DELETED = "sales.comment.deleted.v1"
    SALES_ASSIGNMENT_CHANGED = "sales.assignment.changed.v1"
    SALES_MENTION_CREATED = "sales.mention.created.v1"
    SALES_REVIEW_REQUESTED = "sales.review.requested.v1"
    SALES_REVIEW_APPROVED = "sales.review.approved.v1"
    SALES_REVIEW_CHANGES_REQUESTED = "sales.review.changes_requested.v1"
    SALES_REVIEW_REJECTED = "sales.review.rejected.v1"
    SALES_TRANSFER_COMPLETED = "sales.transfer.completed.v1"


ALL_KNOWN_EVENT_NAMES: frozenset[str] = frozenset(
    getattr(EventNames, name)
    for name in dir(EventNames)
    if name.isupper() and not name.startswith("_")
)
