/**
 * Design System Governance — component maturity registry (E1.6).
 * Evidence-based statuses — do not invent scores beyond listed criteria.
 */

export type ComponentMaturity =
  | 'experimental'
  | 'preview'
  | 'stable'
  | 'legacy'
  | 'deprecated'
  | 'blocked'

export type ComponentHealth = {
  id: string
  name: string
  version: string
  owner: string
  maturity: ComponentMaturity
  lastChange: string
  documentation: boolean
  tests: boolean
  sandbox: boolean
  migrationComplete: boolean
  api: 0 | 1 | 2 // 0 weak / 1 ok / 2 solid
  accessibility: 0 | 1 | 2
  responsive: 0 | 1 | 2
  theme: 0 | 1 | 2
  performance: 0 | 1 | 2
  notes?: string
}

/** Score /10 from binary/ternary criteria (documented in governance doc). */
export function healthScore(h: ComponentHealth): number {
  const bits = [
    h.documentation ? 1 : 0,
    h.tests ? 1 : 0,
    h.sandbox ? 1 : 0,
    h.api,
    h.accessibility,
    h.responsive,
    h.theme,
    h.performance,
  ]
  const max = 1 + 1 + 1 + 2 + 2 + 2 + 2 + 2
  const sum = bits.reduce<number>((a, b) => a + b, 0)
  return Math.round((sum / max) * 100)
}

export const COMPONENT_MATURITY_REGISTRY: readonly ComponentHealth[] = [
  {
    id: 'button',
    name: 'Button',
    version: '1.0',
    owner: 'design-system',
    maturity: 'stable',
    lastChange: 'E1.4',
    documentation: true,
    tests: true,
    sandbox: true,
    migrationComplete: false,
    api: 2,
    accessibility: 2,
    responsive: 2,
    theme: 2,
    performance: 2,
    notes: 'Wraps legacy .btn for parity; migration incomplete app-wide.',
  },
  {
    id: 'input',
    name: 'Input',
    version: '1.0',
    owner: 'design-system',
    maturity: 'stable',
    lastChange: 'E1.6',
    documentation: true,
    tests: true,
    sandbox: false,
    migrationComplete: false,
    api: 2,
    accessibility: 2,
    responsive: 2,
    theme: 2,
    performance: 2,
    notes: 'E1.6: :focus-visible. Still absent from sandbox.',
  },
  {
    id: 'form-field',
    name: 'FormField',
    version: '1.0',
    owner: 'design-system',
    maturity: 'stable',
    lastChange: 'E1.6',
    documentation: true,
    tests: true,
    sandbox: false,
    migrationComplete: false,
    api: 2,
    accessibility: 2,
    responsive: 2,
    theme: 2,
    performance: 2,
    notes: 'E1.6: aria-describedby / aria-invalid wired onto single child control.',
  },
  {
    id: 'badge',
    name: 'Badge',
    version: '1.0',
    owner: 'design-system',
    maturity: 'stable',
    lastChange: 'E1.4',
    documentation: true,
    tests: true,
    sandbox: true,
    migrationComplete: false,
    api: 2,
    accessibility: 2,
    responsive: 2,
    theme: 2,
    performance: 2,
  },
  {
    id: 'empty-state',
    name: 'EmptyState',
    version: '1.0',
    owner: 'design-system',
    maturity: 'preview',
    lastChange: 'E1.4',
    documentation: true,
    tests: true,
    sandbox: false,
    migrationComplete: false,
    api: 2,
    accessibility: 2,
    responsive: 2,
    theme: 2,
    performance: 2,
  },
  {
    id: 'progress',
    name: 'Progress',
    version: '1.0',
    owner: 'design-system',
    maturity: 'preview',
    lastChange: 'E1.4',
    documentation: true,
    tests: true,
    sandbox: false,
    migrationComplete: false,
    api: 2,
    accessibility: 2,
    responsive: 2,
    theme: 2,
    performance: 2,
  },
  {
    id: 'page-header',
    name: 'PageHeader',
    version: '1.0',
    owner: 'design-system',
    maturity: 'preview',
    lastChange: 'E1.4',
    documentation: true,
    tests: true,
    sandbox: false,
    migrationComplete: false,
    api: 2,
    accessibility: 2,
    responsive: 2,
    theme: 2,
    performance: 2,
  },
  {
    id: 'section',
    name: 'Section',
    version: '1.0',
    owner: 'design-system',
    maturity: 'stable',
    lastChange: 'E1.4',
    documentation: true,
    tests: true,
    sandbox: true,
    migrationComplete: false,
    api: 2,
    accessibility: 2,
    responsive: 2,
    theme: 2,
    performance: 2,
  },
  {
    id: 'stat-card',
    name: 'StatCard',
    version: '1.0',
    owner: 'design-system',
    maturity: 'stable',
    lastChange: 'E1.4',
    documentation: true,
    tests: true,
    sandbox: true,
    migrationComplete: false,
    api: 2,
    accessibility: 1,
    responsive: 2,
    theme: 2,
    performance: 2,
    notes: 'Trend colors still use hardcoded HEX for up/down.',
  },
  {
    id: 'metric-card',
    name: 'MetricCard',
    version: '1.0',
    owner: 'design-system',
    maturity: 'stable',
    lastChange: 'E1.4',
    documentation: true,
    tests: true,
    sandbox: true,
    migrationComplete: false,
    api: 2,
    accessibility: 2,
    responsive: 2,
    theme: 2,
    performance: 2,
  },
  {
    id: 'quick-action-card',
    name: 'QuickActionCard',
    version: '1.0',
    owner: 'design-system',
    maturity: 'stable',
    lastChange: 'E1.4',
    documentation: true,
    tests: true,
    sandbox: true,
    migrationComplete: false,
    api: 2,
    accessibility: 2,
    responsive: 2,
    theme: 2,
    performance: 2,
  },
  {
    id: 'container',
    name: 'Container',
    version: '1.0',
    owner: 'design-system',
    maturity: 'stable',
    lastChange: 'E1.4',
    documentation: true,
    tests: true,
    sandbox: true,
    migrationComplete: true,
    api: 2,
    accessibility: 2,
    responsive: 2,
    theme: 2,
    performance: 2,
  },
  {
    id: 'stack',
    name: 'Stack',
    version: '1.0',
    owner: 'design-system',
    maturity: 'stable',
    lastChange: 'E1.4',
    documentation: true,
    tests: true,
    sandbox: true,
    migrationComplete: true,
    api: 2,
    accessibility: 2,
    responsive: 2,
    theme: 2,
    performance: 2,
  },
  {
    id: 'inline',
    name: 'Inline',
    version: '1.0',
    owner: 'design-system',
    maturity: 'stable',
    lastChange: 'E1.4',
    documentation: true,
    tests: true,
    sandbox: true,
    migrationComplete: true,
    api: 2,
    accessibility: 2,
    responsive: 2,
    theme: 2,
    performance: 2,
  },
  {
    id: 'grid',
    name: 'Grid',
    version: '1.0',
    owner: 'design-system',
    maturity: 'stable',
    lastChange: 'E1.4',
    documentation: true,
    tests: true,
    sandbox: true,
    migrationComplete: true,
    api: 2,
    accessibility: 2,
    responsive: 2,
    theme: 2,
    performance: 2,
  },
  {
    id: 'dialog',
    name: 'Dialog',
    version: '1.0',
    owner: 'design-system',
    maturity: 'stable',
    lastChange: 'E1.4.1',
    documentation: true,
    tests: true,
    sandbox: true,
    migrationComplete: false,
    api: 2,
    accessibility: 2,
    responsive: 2,
    theme: 2,
    performance: 2,
  },
  {
    id: 'confirm-dialog',
    name: 'ConfirmDialog',
    version: '1.0',
    owner: 'design-system',
    maturity: 'stable',
    lastChange: 'E1.4.1',
    documentation: true,
    tests: true,
    sandbox: true,
    migrationComplete: false,
    api: 2,
    accessibility: 2,
    responsive: 2,
    theme: 2,
    performance: 2,
    notes: '~16 files still use window.confirm.',
  },
  {
    id: 'drawer',
    name: 'Drawer',
    version: '1.0',
    owner: 'design-system',
    maturity: 'stable',
    lastChange: 'E1.4.1',
    documentation: true,
    tests: true,
    sandbox: true,
    migrationComplete: false,
    api: 2,
    accessibility: 2,
    responsive: 2,
    theme: 2,
    performance: 2,
  },
  {
    id: 'tooltip',
    name: 'Tooltip',
    version: '1.0',
    owner: 'design-system',
    maturity: 'preview',
    lastChange: 'E1.4.1',
    documentation: true,
    tests: true,
    sandbox: true,
    migrationComplete: false,
    api: 2,
    accessibility: 2,
    responsive: 1,
    theme: 2,
    performance: 2,
    notes: 'Option B CSS placement — no Floating UI collision detection.',
  },
  {
    id: 'popover',
    name: 'Popover',
    version: '1.0',
    owner: 'design-system',
    maturity: 'preview',
    lastChange: 'E1.4.1',
    documentation: true,
    tests: true,
    sandbox: true,
    migrationComplete: false,
    api: 2,
    accessibility: 1,
    responsive: 1,
    theme: 2,
    performance: 2,
    notes: 'Lightweight; not a full menu system.',
  },
  {
    id: 'overlay-provider',
    name: 'OverlayProvider',
    version: '1.0',
    owner: 'design-system',
    maturity: 'stable',
    lastChange: 'E1.4.1',
    documentation: true,
    tests: true,
    sandbox: false,
    migrationComplete: true,
    api: 2,
    accessibility: 2,
    responsive: 2,
    theme: 2,
    performance: 2,
  },
  {
    id: 'app-launcher',
    name: 'AppLauncher',
    version: '1.0',
    owner: 'design-system',
    maturity: 'stable',
    lastChange: 'E1.5',
    documentation: true,
    tests: true,
    sandbox: true,
    migrationComplete: true,
    api: 2,
    accessibility: 2,
    responsive: 2,
    theme: 2,
    performance: 2,
  },
  {
    id: 'product-mark',
    name: 'ProductMark',
    version: '1.0',
    owner: 'design-system',
    maturity: 'preview',
    lastChange: 'E1.5',
    documentation: true,
    tests: true,
    sandbox: false,
    migrationComplete: true,
    api: 2,
    accessibility: 2,
    responsive: 2,
    theme: 2,
    performance: 2,
  },
] as const

export type DesignScoreCategory = {
  id: string
  label: string
  score: number
  rationale: string
}

/**
 * Global design scores — each /100 grounded in audit evidence (E1.6).
 * Do not inflate; document rationale in design-system-qa-report-v1.md.
 */
export const DESIGN_SCORE_CATEGORIES: readonly DesignScoreCategory[] = [
  {
    id: 'architecture',
    label: 'Architecture',
    score: 88,
    rationale: 'Registry, Theme Engine, overlays, launcher modules separated; no parallel DS.',
  },
  {
    id: 'accessibility',
    label: 'Accessibilité',
    score: 78,
    rationale: 'Overlays/Launcher solid; FormField aria wired E1.6; Input :focus-visible; legacy modals remain.',
  },
  {
    id: 'responsive',
    label: 'Responsive',
    score: 78,
    rationale: 'Shell 1024 + launcher Drawer; many ad-hoc breakpoints in index.css remain.',
  },
  {
    id: 'theming',
    label: 'Theming',
    score: 80,
    rationale: 'Pilot tokens live; dual legacy --forest/--ink still dominate index.css.',
  },
  {
    id: 'components',
    label: 'Components',
    score: 82,
    rationale: 'V1 set complete + tested; sandbox gaps for Input/FormField/EmptyState/Progress.',
  },
  {
    id: 'motion',
    label: 'Motion',
    score: 75,
    rationale: 'Tokens + reduced-motion in overlays/components/launcher; unused instant/exit.',
  },
  {
    id: 'performance',
    label: 'Performance',
    score: 84,
    rationale: 'Overlays code-split; launcher light; no Sales/Doc bundles.',
  },
  {
    id: 'documentation',
    label: 'Documentation',
    score: 92,
    rationale: 'E1.1–E1.7 docs complete: manifesto, contributing, gates, certification, release notes.',
  },
  {
    id: 'tests',
    label: 'Tests',
    score: 86,
    rationale: '~139 DS+launcher tests with jsdom RTL for overlays/launcher.',
  },
  {
    id: 'migration',
    label: 'Migration',
    score: 48,
    rationale: '~318 .btn usages, 18 window.confirm, local ConfirmDialog still present.',
  },
  {
    id: 'legacy',
    label: 'Legacy control',
    score: 42,
    rationale: 'index.css ~232 HEX; dual token systems; suppression not started (by design).',
  },
]

export function globalDesignScore(): number {
  const sum = DESIGN_SCORE_CATEGORIES.reduce((a, c) => a + c.score, 0)
  return Math.round(sum / DESIGN_SCORE_CATEGORIES.length)
}

export type PilotReadiness = 'design_ready' | 'partially_ready' | 'not_ready'

export type PilotReadinessRow = {
  productId: string
  readiness: PilotReadiness
  why: string
}

export const PILOT_READINESS: readonly PilotReadinessRow[] = [
  {
    productId: 'comptapilot',
    readiness: 'design_ready',
    why: 'Active runtime, theme parity, launcher active, migrated surfaces (dashboard/workqueue/setup).',
  },
  {
    productId: 'elfis-core',
    readiness: 'partially_ready',
    why: 'Platform identity + launcher header; no product shell route for workspace users.',
  },
  {
    productId: 'salespilot',
    readiness: 'partially_ready',
    why: 'CRM + dashboard + pipeline board (S1.3); beta DEV; fiche complète / Kanban avancé plus tard.',
  },
  {
    productId: 'docpilot',
    readiness: 'partially_ready',
    why: 'Theme/sandbox ready; coming_soon; no SPA routes.',
  },
  {
    productId: 'hrpilot',
    readiness: 'not_ready',
    why: 'Registry + palette only; launcher chip; no theme consumption in product UI.',
  },
  {
    productId: 'legalpilot',
    readiness: 'not_ready',
    why: 'Registry + palette only; no application shell.',
  },
  {
    productId: 'inventorypilot',
    readiness: 'not_ready',
    why: 'Registry only.',
  },
  {
    productId: 'marketingpilot',
    readiness: 'not_ready',
    why: 'Registry only.',
  },
  {
    productId: 'projectpilot',
    readiness: 'not_ready',
    why: 'Registry only.',
  },
  {
    productId: 'supportpilot',
    readiness: 'not_ready',
    why: 'Registry only.',
  },
]
